# Generated by Django 6.0.2 on 2026-02-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='course',
            name='tabs',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
