# Generated by Django 6.0.2 on 2026-02-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_created_at_course_modules_course_tabs_and_more'),
        ('students', '0004_alter_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='students.student'),
        ),
    ]
